//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyCare.Exception {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceErrorMessages() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyCare.Exception.ResourceErrorMessages", typeof(ResourceErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Category is invalid or null..
        /// </summary>
        public static string CATEGORY_EMPTY {
            get {
                return ResourceManager.GetString("CATEGORY_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a An error occurred! Unable to Create!.
        /// </summary>
        public static string CREATE_MESSAGE_ERROR {
            get {
                return ResourceManager.GetString("CREATE_MESSAGE_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Create User - Error!.
        /// </summary>
        public static string CREATE_TITLE_ERROR {
            get {
                return ResourceManager.GetString("CREATE_TITLE_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a An error occurred! Unable to Delete!.
        /// </summary>
        public static string DELETE_ERROR_MESSAGE {
            get {
                return ResourceManager.GetString("DELETE_ERROR_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Delete  - Error!.
        /// </summary>
        public static string DELETE_ERROR_TITLE {
            get {
                return ResourceManager.GetString("DELETE_ERROR_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Description is invalid or null..
        /// </summary>
        public static string DESCRIPTION_EMPTY {
            get {
                return ResourceManager.GetString("DESCRIPTION_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a An error occurred! Unable to Edit!.
        /// </summary>
        public static string EDIT_ERROR_MESSAGE {
            get {
                return ResourceManager.GetString("EDIT_ERROR_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Edit - Error!.
        /// </summary>
        public static string EDIT_ERROR_TITLE {
            get {
                return ResourceManager.GetString("EDIT_ERROR_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Credentials error: Email already registered..
        /// </summary>
        public static string EMAIL_ALREADY_REGISTERED {
            get {
                return ResourceManager.GetString("EMAIL_ALREADY_REGISTERED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Email is invalid or null..
        /// </summary>
        public static string EMAIL_EMPTY {
            get {
                return ResourceManager.GetString("EMAIL_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a An error occurred! Unable to get by ID!.
        /// </summary>
        public static string GET_BY_ID_ERROR_MESSAGE {
            get {
                return ResourceManager.GetString("GET_BY_ID_ERROR_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Get by ID - Error!.
        /// </summary>
        public static string GET_BY_ID_ERROR_TITLE {
            get {
                return ResourceManager.GetString("GET_BY_ID_ERROR_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a No records with this id found!.
        /// </summary>
        public static string ID_ERROR {
            get {
                return ResourceManager.GetString("ID_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a An error occurred! Unable to list..
        /// </summary>
        public static string LIST_ERROR_MESSAGE {
            get {
                return ResourceManager.GetString("LIST_ERROR_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a List - Error!.
        /// </summary>
        public static string LIST_ERROR_TITLE {
            get {
                return ResourceManager.GetString("LIST_ERROR_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a An error occurred! Unable to complete log In!.
        /// </summary>
        public static string LOG_IN_ERROR_MESSAGE {
            get {
                return ResourceManager.GetString("LOG_IN_ERROR_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Log In - Error!.
        /// </summary>
        public static string LOG_IN_ERROR_TITLE {
            get {
                return ResourceManager.GetString("LOG_IN_ERROR_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Manufacturer is invalid or null..
        /// </summary>
        public static string MANUFACTURER_EMPTY {
            get {
                return ResourceManager.GetString("MANUFACTURER_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Name is invalid or null..
        /// </summary>
        public static string NAME_EMPTY {
            get {
                return ResourceManager.GetString("NAME_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a No records found!.
        /// </summary>
        public static string NO_REGISTRY {
            get {
                return ResourceManager.GetString("NO_REGISTRY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The passwords entered do not match..
        /// </summary>
        public static string PASSWORD_CONFIRM_ERROR {
            get {
                return ResourceManager.GetString("PASSWORD_CONFIRM_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Password is invalid or null..
        /// </summary>
        public static string PASSWORD_EMPTY {
            get {
                return ResourceManager.GetString("PASSWORD_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Reference is invalid or null..
        /// </summary>
        public static string REFERENCE_EMPTY {
            get {
                return ResourceManager.GetString("REFERENCE_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Status is invalid or null..
        /// </summary>
        public static string STATUS_EMPTY {
            get {
                return ResourceManager.GetString("STATUS_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a An unknown error has occurred..
        /// </summary>
        public static string UNKNOWN_ERROR {
            get {
                return ResourceManager.GetString("UNKNOWN_ERROR", resourceCulture);
            }
        }
    }
}
